### ISSUE TITLE
Return the archived/unarchived file path

### ISSUE THREAD

**Issue by yangyadi1993** [mholt/archiver#130]
## What would you like to have changed?

Currently, only the error message will be returned when we unarchived files. I don't know what the archived file path is. If the archived path could be returned, it will be more user friendly.

Just asking if you have the plans :)

**Comment by mholt** [comment]
I don't fully understand what you mean. It's not specific enough. If you could fill out the full issue template, complete with code examples in this case that would be helpful, thanks.

**Comment by J7mbo** [comment]
@mholt  I think that this issue is related to [this](https://github.com/golang/go/issues/32300).

I'm looping around a zip of a bitbucket repo. I'm trying to extract all text files that are mine and **not** in vendor. 

When looking at your `FileInfo` provided from `Walk()`, getting to a vendor/ directory, the `Name()` function only contains the name of the file, not the path itself (which is weird because when debugging I can see the path). Also `FileInfo` when printed only contains the name of the file too.

As a result, I can't exclude the text files from vendor with a `strings.Contains()`

Any chance that the path of the file can be included alongside the `FileInfo`? I'm happy to create a new issue but would rather know if there's the option for this first.

**Comment by ZaynJarvis** [comment]
like the filepath.Walk
https://golang.org/pkg/path/filepath/#WalkFunc

**Comment by mholt** [comment]
I think this is implemented in #302, as NameInArchive, if I understand correctly.
