### ISSUE TITLE
Why did Compress and Uncompress disappear?

### ISSUE THREAD

**Issue by simonjohansson** [mholt/archiver#131]
Howdy and thanks for a awesome library!

We have a use case where we tar up a path and upload it to google cloud storage, which takes a []byte as the object you wish to upload. Later on we might download the tar which again gives us a []byte and untar it to some path.

In `v2.0.1` we have the super helpful

```
Compress(sourceDir string) (tar []byte, err error)
Uncompress(destinationDir string, tar []byte) (err error)
```

We noticed that we had issues with the symlink and that later versions of archiver fixes this. But the helpful functions are now gone in favor of 

```
Archive(sources []string, destination string) error
Unarchive(source, destination string) error
```

Any reason why there are no methods do archive into []byte and unarchive from []byte anymore?

**Comment by mholt** [comment]
Hmm, I can't find those functions in the commit history -- do you have a link to them to refresh my memory?

In any case, I think it must have been removed because the use case for buffering entire archive files in memory as byte slices was limited. It's much more recommended to stream instead. (How would you upload large objects to the cloud? That API sounds terrible...) There are examples how to do this in the godocs: https://godoc.org/github.com/mholt/archiver#example-Zip--StreamingWrite

**Comment by mholt** [comment]
Hm, okay -- I'll tag this as a feature request; contributions welcomed.

**Comment by hoster110** [comment]
My idea is to use full IO to accelerate the compression efficiency;
1. Can multi-threading be supported?
2. Can you write zip file in an additional way to adapt to the memory shortage caused by large files?

**Comment by hoster110** [comment]
func Zip(srcFile string, destZip string, thNums string) error {
	SytemToInfo()
	err := filepath.Walk(srcFile,Listfunc)
	if err != nil {
		Err(err)
		return err
	}
	nums, err := strconv.ParseInt(thNums,10,32)
	if err != nil {
		Err(err)
		return err
	}

	batchsize := 2

	for index := 0; index < len(ListFile); index = index+batchsize{

		wg.Add(1)
		go func (i int){
			buf := new(bytes.Buffer)
			archive := zip.NewWriter(buf)

			defer archive.Close()
			for in := i;in < i+batchsize && in < len(ListFile);in++{
				ff, err := archive.Create(ListFile[in])
				if err != nil {
					Err(err)
					continue
				}

				bytes,err := ioutil.ReadFile(ListFile[in])
				_, err = ff.Write(bytes)
				if err != nil {
					Err(err)
					continue
				}

			}
			err = archive.Close()
			if err != nil {
				Err(err)
				return
			}
	
			mx.Lock()
			f, err := os.OpenFile(destZip, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
			if err != nil {
				Err(err)
				os.Exit(-1)
			}
			Info(fmt.Sprintf("[%+v] [Start Writing to File!!!]",i))
			buf.WriteTo(f)
			Info(fmt.Sprintf("[%+v] [Writing to File The End!!!]",i))
			f.Close()
			mx.Unlock()
			wg.Done()
		}(index)

		if index % int(nums) == 0{
			wg.Wait()
		}

	}

	wg.Wait()
	return nil
}

**Comment by nmiyake** [comment]
I've put up PRs #199 and #200 that would mostly do this.

Previously, there was:

```
type Archiver interface {
...
	// Write writes an archive to a Writer.
	Write(output io.Writer, sources []string) error
	// Read reads an archive from a Reader.
	Read(input io.Reader, destination string) error
}
```

Those PRs would introduce:

```
type ReaderUnarchiver interface {
	ReaderUnarchive(source io.Reader, size int64, destination string) error
}
type WriterArchiver interface {
	WriterArchive(sources []string, destination io.Writer) error
}
```

Besides the argument order being swapped and the names being different, the other primary difference is that the "Read" function takes a "size" parameter. This is not required for tar or rar archives, but is required for zip archives -- removing the "size" parameter would force the implementation to fully read the archive into memory first, which is not efficient.

However, consumers should be able to deal with this trivially with a wrapper interface -- if you know that you're not going to deal with zip archives, you can just pass "0" for the size parameter (and if you do need zip support, you can check for it and then do the work of reading the bytes into memory and getting the size yourself).

I think this approach (exposing size parameter as part of API to allow more efficiency) is better than having the native approach omit size and read into memory for ZIP (which is what it did previously) since it allows for more efficiency while still allowing clients the flexibility to work around it with their own API if needed.

**Comment by mholt** [comment]
Thanks for all the work on this, I will get back to this sometime after Caddy 2 is in a more polished state.

**Comment by nmiyake** [comment]
@mholt hi, was wondering whether you might have bandwidth to take a look at this sometime in the near future? I've run into a place where this would be helpful to have again. It's been a while since the PR and last update to the issue, but if you think you'd be able to take a look then I can iterate on it as needed.

**Comment by bfirsh** [comment]
Thanks @nmiyake for your help here. I have made a branch that includes both #199 and #200, because I needed both in a project.

For folks reading this, it's a bit of a convoluted process to actually use the fork. Run `go get github.com/mholt/archiver/v3`, add then add this line to the end of `go.mod`:

    replace github.com/mholt/archiver/v3 => github.com/bfirsh/archiver/v3 reader-writer

Then, import `github.com/mholt/archiver/v3` somewhere in your code and run `go mod tidy`. That'll then replace the above line with a psuedo-version pointing at the actual commit.

**Comment by mholt** [comment]
During the holidays I took some time and completely rewrote this library in #302 and am preparing to merge and tag it as v4. The new core APIs are completely stream-oriented, so I believe that should resolve this issue.
