### ISSUE TITLE
Misleading error message if you create an archive with incorrect name on Windows

### ISSUE THREAD

**Issue by Senpos** [mholt/archiver#157]
## What version of the package or command are you using?
Since I installed less than an hour ago, I guess, this is it: [2bd00e47f6e10b3199ae839ca3ccaea9c9f3aa32](https://github.com/mholt/archiver/commit/2bd00e47f6e10b3199ae839ca3ccaea9c9f3aa32)

## What are you trying to do?
I was trying to create an archive which contains forbidden (in Windows) character in its name: `\/:*?"<>|`

## What steps did you take?
Considering you have a file `demo.txt` in the CWD
```go
func main() {
	src := "demo.txt"
	dst := "*demo.zip"
	err := archiver.Archive([]string{src}, dst)
	if err != nil {
		log.Fatal(err)
	}
}
```

## What did I expect to happen?
To see a better error saying that archive was not created because of system or FS problem or something like that

## What actually happened instead?
I received an error, which says that **file already exists:**
`2019/03/23 22:42:26 file already exists: *demo.zip`
Which is confusing, because file was not even created, because it can't be created with such name

## How do you think this should be fixed?
I don't know if this can be determined easily
But for example - checking prohibited characters in the target path if OS is Windows? :)

## Bonus: What do you use archiver for, and do you find it useful?
Doing a simple utility to backup my game saves every N minutes, so I won't lose them :)
Despite the power of golang stdlib, it feels too low-level sometimes, so I found archiver very convenient tool, thank you for making it

**Comment by mholt** [comment]
This is tricky because that error message comes from Windows. Who are we to say it's wrong? 😕 

Anyway, I don't really know what to do about it... and #302 (which will be v4.0) will not write directly to the disk, at least not in the core APIs. (Maybe some convenience or API functions will in the future.)

Thanks for raising the issue, but will close it as it might be obsoleted soon. Can continue discussion or reopen if needed.
