### ISSUE TITLE
Consecutively zipping same files have same hashes unlike native zip behavior.

### ISSUE THREAD

**Issue by christopinka** [mholt/archiver#168]
## What version of the package or command are you using?
3.1.1

## What are you trying to do?
Compare sha1 hashes from zipped files after consecutive zipping

## What steps did you take?
execute - $arc arc -overwrite -folder-safe archive dest.zip source_foler

## What did you expect to happen, and what actually happened instead?
zipped file hashes have different hashes after consecutive zipping. Instead, arc seems to solve this problem but doesn't behave the same as native zip. Is this purposeful? Inadvertent?

## How do you think this should be fixed?
Determine why the arc behaves differently than native zip.

## Please link to any related issues, pull requests, and/or discussion
https://stackoverflow.com/questions/11603615/zip-files-contain-same-files-but-have-different-hashes

## Bonus: What do you use archiver for, and do you find it useful?
Potential of streaming archives and cross-platform support.

**Comment by mholt** [comment]
I'd say that a reproducible hash is a feature, not a bug. 🤷‍♂

And the question is impossible to answer without a zip archive to compare against. We'd need the source files, and the archives created by both methods, for inspection. (I'm not saying I have time to look at them in depth right now, since I see this as a non-issue, but in order for anyone else to answer it, there'd have to be a lot more information.)
