### ISSUE TITLE
Subdirectory names get dropped

### ISSUE THREAD

**Issue by frankh** [mholt/archiver#250]
## What version of the package or command are you using?
`arc v3.3.2 c7eae9dcbcb1f0a0ce965184868097babf73d415 (2020-09-29T18:23:13Z)`

## What are you trying to do?
create an archive of a file multiple directories deep

## What steps did you take?
`arc archive test.tar.gz mobile/vendor/bundle`

the only file is `mobile/vendor/bundle/file.txt`

## What did you expect to happen, and what actually happened instead?
expected test.tar.gz to contain `mobile/vendor/bundle/file.txt`
actually contained `bundle/file.txt`

## How do you think this should be fixed?
should match `tar` cli behaviour. `tar czf test.tar.gz mobile/vendor/bundle` creates the archive i expect and extracts to `mobile/vendor/bundle/file.txt` instead of just `bundle/file.txt`

**Comment by coolaj86** [comment]
@frankh Thanks for the report. This seems like a bug to me that should get fixed.

@mholt Can you confirm that this should be a fix in v3.x, or should this sort of change in behavior cause a bump to v4? And was this intended?

**Comment by mholt** [comment]
Hmmm I think this is intentional: you're specifying a folder by name, the "bundle" folder -- the fact that it happens to be nested in two directories relative to the current path is irrelevant. In other words, it's intentional that the current environment including path is irrelevant to archiving specified files. The structure _within_ the specified folders is all that matters.

I am not sure how to express mappings from file inputs to archival paths in the CLI.

**Comment by coolaj86** [comment]
Ah, I see. So `archiver` always operates as if it has the equivalent of `tar`s `-C`.

I think that's different from the common convention of how most other archive programs work, and it does make it difficult to specify a parent directory structure, but I can see how the existing behavior is rational.

**Comment by mholt** [comment]
I always thought tar was confusing. Why does my current path make any difference as to how the archive is made? That's tedious. Just archive the files I specify.

IMO the simplest and most straightforward way to craft a custom archive structure is to literally just craft the structure on disk, then archive that folder.

**Comment by coolaj86** [comment]
I think it's because on a traditional Unix system you want to unpack things in a particular "FHS" style.

Anyway: Tomato, potato.

`archiver` is not `tar`. Closed.

**Comment by d-Rickyy-b** [comment]
Hi @mholt 

>Why does my current path make any difference as to how the archive is made?

> the simplest and most straightforward way to craft a custom archive structure is to literally just craft the structure on disk, then archive that folder, rather than trying to map each file to a destination path.
You might not want to archive every subdirectory within your crafted structure. So you might specify a more deeply nested directory but want to preserve higher directories (maybe even up to the file system root) for restoring the files later on.

An example:

Imagine you are storing files in /home/rico/project/ and within that directory you have the following structure:
```
project/
├── huge_files
├── images
├── src
└── tmp
```

Now I'd prefer to get an archive file with the contents of `src` and `images` and avoid adding the tmp and "huge" files to my archive, because that's not what I need in this case. On the other hand I still want to preserve the directory structure to know "where it belongs to". Maybe I have several projects all having a "src" folder. Knowing by the archive paths where which archive belongs to is quite helpful. The final archive would contain the following paths & files:

```
/home/rico/project/src/<files>
/home/rico/project/images/<files>
```

To me that issue is quite bigger that what the original poster wrote, so I created an extra issue for it (#262).

**Comment by mholt** [comment]
#302, a complete rewrite for the upcoming v4 tag, will let you specify exact file paths you want for each file in your archive.
