### ISSUE TITLE
Dereference symlinks flag for FilesFromDisk

### ISSUE THREAD

**Issue by korpa** [mholt/archiver#303]
## What would you like to have changed?

Instead of adding the symlink into archive, it should add the content of the target file of the symlink if the flag is set. Similar to https://www.gnu.org/software/tar/manual/html_node/dereference.html

**Comment by mholt** [comment]
Thanks for the request. I don't think anything needs to change about `Archive()`'s signature to do what you want. All `Archive()` does is create an archive with the files in the list. To dereference symlinks, don't create a `File` with a `FileInfo` that sets the SymLink flag and has `LinkTarget` set. Instead, create a `File` with an `Open` func set and `LinkTarget` unset/empty.

Does that make sense? So basically you'll do the dereferencing the way you want, instead of leaving that up to the archiver package.

(Closing, but feel free to continue discussion. We can reopen if needed.)

**Comment by korpa** [comment]
I'm not sure if I understand what you mean. Currently I use `archiver.FilesFromDisk` so I haven't touched any functions you mention, yet. I will have a look at at your proposal and try to understand.

On the other hand, maybe it would make sense to add a dereference flag to `FilesFromDisk`.

**Comment by korpa** [comment]
I had a look at `FilesFromDisk` and now got what you mean.

I could implement my own `FilesFromDisk`, but I think a dereference option would be a good fit in the official `FilesFromDisk` function. 
What do you think?

**Comment by mholt** [comment]
Ah, yeah, that's a totally separate function from what was mentioned originally.

Maybe it would make sense for that function to take options. I'm mobile right now but we could discuss a few ideas. 👍

**Comment by korpa** [comment]
I added a pull request but I'm not sure if it is the best solution. Let's discuss.
