### ISSUE TITLE
Brotli identification inconsistent

### ISSUE THREAD

**Issue by jhwz** [mholt/archiver#317]
## What version of the package or command are you using?
v4.0.0-alpha.4

## What are you trying to do?
Open a `.br` file and read its contents through the Identify API 

## What steps did you take?

Here's a reproduction with a test file containing the given text that was compressed via a `brotli` CLI tool
```
func TestReproduce(t *testing.T) {
	const contents = "some text in a file\n"

	f, err := os.Open("testdata/compression/raw.br")
	require.NoError(t, err)

	format, err := archiver.Identify("testdata/compression/raw.br", f)
	require.NoError(t, err)

	rc, err := format.(archiver.Decompressor).OpenReader(f)
	require.NoError(t, err)

	data, err := io.ReadAll(rc)
	require.NoError(t, err)

	assert.Equal(t, contents, string(data))

	assert.NoError(t, rc.Close())
}
```

## What did you expect to happen, and what actually happened instead?
File should be consistently detected, instead sometimes it works OK and other times it returns one of the following errors:
```
matching rar: brotli: PADDING_1
matching zip: brotli: PADDING_1
```

## How do you think this should be fixed?
I think its returning inconsistent errors because the formats are stored in a map? Making the test non-deterministic. I'm not sure what the underlying issue is though!

## Bonus: What do you use archiver for, and do you find it useful?
We're using archiver for our CLI tooling to easily support a wide range of compression formats. Was trying out the new library version and caught this issue!

**Comment by jhwz** [comment]
Ah interesting I'm finding a related issue with `.bz2` files sometimes: 

```matching zip: bzip2: corrupted input: invalid stream magic```

**Comment by mholt** [comment]
That's very odd/interesting!...

Map iteration might be one factor, yes; we also do some stream seeking to be able to read from the beginning multiple times. (If that turns out to be problematic, another way to do that is to read the beginning of the stream and buffer it, then replace the input stream with a MultiReader that first reads from the buffer, then from the remaining stream... but that's more complicated.)

Brotli can only match by filename since brotli unfortunately doesn't have any particular header or preface/prefix to look for. Dunno if that matters, but thought I'd point that out.

Can you post a reproducible test case? Both the input file and a functional test (that just uses std lib). Then I can take a look at some point. Or if you want to dig in further, that'd be helpful too.

**Comment by jhwz** [comment]
I'll add one soon but have a look first! If I can help and save you a bit of time then that would be ideal.

One nice thing about the buffering/multireader approach is that you would be able to support just io.Readers and wouldn't require the Seek method. Would be a bit more complex but would also be convenient! Maybe you could guarantee the returned reader will always keep reading from the same point even if there is an error so the user can do something else with the stream instead?

**Comment by mholt** [comment]
Yeah, that's also appealing. That's the approach I take in [Caddy's layer 4 module](https://github.com/mholt/caddy-l4) which previews the stream to do some matching logic and it seems to work well. But that API also is better about wrapping streams and using buffers and stuff. We can make any changes we need to in our API to accommodate, since it's still pre-release alpha versions.

**Comment by mholt** [comment]
@jhwz Does your PR (#322) fix this issue? Or was that separate.

**Comment by jhwz** [comment]
Just ran the tests and they're still failing. I'll try investigate some more.

**Comment by jhwz** [comment]
Hmm it seems I may have got something wrong - I went through and rebuilt some of the tests and have now got them in a state where they are passing... :disappointed: Hopefully it's my mistake!
