### ISSUE TITLE
v4: archiver.FileSystem is substantially slower than Extract() when walking the file system

### ISSUE THREAD

**Issue by dcermak** [mholt/archiver#326]
## What version of the package or command are you using?

`github.com/mholt/archiver/v4 v4.0.0-alpha.5`

## What are you trying to do?

I would like to walk all files in an archive and retrieve their file sizes for later visualization.

## What steps did you take?

I first looked into the `archiver.FileSystem` feature and combined it with `fs.WalkDir`. However this turned out to be exceptionally slow: walking a small archive (~5MB) took 10 to 20s, which is much slower than what I got with the `Walk` function from v3 of this library.

The code for this looked roughly like this:
```go
		  fsys, err := archiver.FileSystem(archivePath)
		  if err != nil {
		  	return nil, err
		  }

		  if err := fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
		  	if err != nil {
		  		return err
		  	}
		  	if d.IsDir() {
		  		return nil
		  	}
		  	if info, err := d.Info(); err != nil {
		  		return err
		  	} else {
		  		// this does the size tracking
		  		root.InsertIntoDir(path, info.Size())
		  		return nil
		  	}
		  }); err != nil {
		  	return nil, err
		  }
```

Thus I looked at `Extract` with a custom handler and this turned out to be much, much faster (and about as fast as v3):

```go
f, err := os.Open(archivePath)
if err != nil {
	return nil, err
}

format, err := archiver.Identify(archivePath, f)
if err != nil {
	return nil, err
}

if ex, ok := format.(archiver.Extractor); ok {
	err := ex.Extract(backgroundContext, f, nil, func(ctx context.Context, f archiver.File) error {
		if f.IsDir() {
			return nil
		}
		root.InsertIntoDir(f.NameInArchive, f.Size())
		return nil
	})
	if err != nil {
		return nil, err
	}
} else {
	return nil, errors.New(fmt.Sprintf("%u is not an Extractor", ex))
}

```
## What did you expect to happen, and what actually happened instead?

I would have expected the `archiver.FileSystem` to be a bit slower, maybe about a factor of two or so as it might not be able to rely on reading sequentially. However, the speed difference was at least an order of magnitude.

## How do you think this should be fixed?

Unfortunately, I don't know.

## Bonus: What do you use archiver for, and do you find it useful?

I use it to extract and analyze the layers of container images in https://github.com/dcermak/container-layer-sizes, which is a visualizer of the sizes of layers in a container image.

**Comment by mholt** [comment]
Thanks for the report. That sounds pretty abysmal.

How many files are in the 5 MB archive?

Go's `io/fs.WalkDir` function calls `ReadDir()` for every entry, and in order to read a single directory to satisfy that interface, we have to walk the whole archive to ensure we got all the files in that dir, then append them to a slice, then finally return the slice. In other words, I believe WalkDir might have O(n^2) performance. So that wouldn't really surprise me.

If you can attach the exact file and code that reproduces the issue, I can investigate. Otherwise I'll just have to guess.

**Comment by dcermak** [comment]
> Thanks for the report. That sounds pretty abysmal.
> 
> How many files are in the 5 MB archive?

That archive was the file system of the alpine image from dockerhub, which has about 58k files. But for my usecase I'd like to use it on much larger archives with potentially a lot more files.

> Go's `io/fs.WalkDir` function calls `ReadDir()` for every entry, and in order to read a single directory to satisfy that interface, we have to walk the whole archive to ensure we got all the files in that dir, then append them to a slice, then finally return the slice. In other words, I believe WalkDir might have O(n^2) performance. So that wouldn't really surprise me.

Yes, that sounds like it could be the problem.
 
> If you can attach the exact file and code that reproduces the issue, I can investigate. Otherwise I'll just have to guess.

Here you go: https://gist.github.com/dcermak/c26486c0dfd877fbf178da4d95d5efea

**Comment by mholt** [comment]
Thanks for that. So yeah, it looks like my hunch is correct.

Calling `Extract()` with a `nil` filter simply walks the archive directly: `O(n)`

Calling `fs.WalkDir()` recursively invokes `ArchiveFS.ReadDir()` for every directory that is discovered. And each call to `ReadDir()` calls `Extract()` with a nil filename filter. In other words, for every directory in the archive, the entire archive is walked looking for files in the specific directory named by `ReadDir()`. And we have to walk the entire archive because archives aren't necessarily ordered breadth-first. (In fact we have special handling and comments in the code for archives created depth-first.) This is approximately `O(n^2)`.

Unfortunately, I don't know a good way to fix this. The file system API and the archive formats are not exactly compatible for performance: `fs.WalkDir` requires a certain order (breadth-first, top-down), and `Extract()` simply iterates the files in an archive, whatever the order.

Yours is definitely worst-case, where you're walking the _entire_ archive. So your `fs.WalkDir()` needs to hit every single file in the archive, but in a specific order. If you narrow your root from `.` to `some/path/deep/within` I bet it will perform much, much better.

Maybe we could introduce a "fast" mode that incorrectly lists all the files including subfolders and their contents within the given root and skips the subfolders themselves, but that would of course be problematic if you did want to enumerate the folders too, or skip some folders. So I'm not sure I love that.

I dunno. Have any ideas/thoughts?

**Comment by dcermak** [comment]
Well, I'd first like to just emphasize that using `Extract()` is more than fine for me, I don't really need the `fs.WalkDir()` API. It merely looked a bit more convenient to use, so I gave it a try and was puzzled by it being so slow.

> I dunno. Have any ideas/thoughts?

The fast mode sounds like a good idea, as I personally doubt that many users are relying on the correct ordering when calling `fs.WalkDir()`.

Given the constraints of this problem, I'd honestly just document this issue as a catch and advice users who really need the performance to use `Extract()` with a `nil` filter (or the fast mode, if you go for that one), thereby forgoing the ordering guarantees but getting speed back.

**Comment by mholt** [comment]
Sounds good, I'll add a comment to the godoc explaining the performance penalty of ArchiveFS for archives with lots of files. And we'll go from there!

**Comment by dcermak** [comment]
Thanks a lot @mholt!

**Comment by mholt** [comment]
FWIW, I've rewritten how ArchiveFS works especially with `fs.WalkDir()`, so it's 10x faster in my testing. Will go out with the beta 9 release.
