### ISSUE TITLE
archiver.Walk() returns files in root without files in subfolders

### ISSUE THREAD

**Issue by nicola-spb** [mholt/archiver#330]
## What version of the package or command are you using?
version v4.0.0-alpha.6 

## What are you trying to do?
I have big zip archive (33 gb) with files and folders with files. I wanna walk in archive and get all files.
ZIP archive: https://fias-file.nalog.ru/downloads/2022.04.12/gar_xml.zip

## What steps did you take?
1) walk in archive
```
fsys, err := archiver.FileSystem(sourcePath)
if err != nil {
	return err
}

err = fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
	println(path)
	if err != nil {
		return err
	}
}
```

2) extract in archive
```
file, err := os.Open(sourcePath)
if err != nil {
	return err
}
defer file.Close()

format := archiver.Zip{}
err = format.Extract(context.Background(), file, nil, func(ctx context.Context, f archiver.File) error {
	println(f.Name())
	return nil
})
if err != nil {
	return err
}

```
## What did you expect to happen, and what actually happened instead?
When I use archiver.Walk then I get all files in root but I didn't get sub folders with files. But when I do it with archiver.Extract then I get all files (with files in folders). It depend on archive. I unzipped archive and recreated archive with one subfolder and root files and archiver.Walk return all files with this folder.

**Comment by mholt** [comment]
It appears this particular zip file does not have actual entries for the subfolders. :man_shrugging: I will have to see about adding logic for _inferring_ them, but this might be dicey if no actual entry exists.

**Comment by nicola-spb** [comment]
Maybe you are right because when I using archiver.Extract I see only file paths without folder.

You can test on this file (38Mb): https://fias-file.nalog.ru/downloads/2022.04.12/gar_delta_xml.zip

**Comment by mholt** [comment]
I have a potential fix implemented, but I want to verify it with some other archives I have laying around when I have a chance.

I'm not sure I love it though. It basically involves discovering/inferring directories from file paths, then faking a directory entry when a _real_ directory entry isn't found. This requires kind of faking some information about the directory if its `FileInfo` is queried, for example its mode.

I think it'll likely be fine, but it does mean that calls to `ReadDir()` (which is what `fs.WalkDir()` uses) will return entries that don't actually exist. 🤔 😮‍💨  I am worried that could break some users. Or maybe not. I don't know. I think it only makes sense for a subfolder to be discoverable when reading its directory so that you can traverse into it. But it also means we're kind of lying.

Sigh. I don't know. Thoughts?

**Comment by nicola-spb** [comment]
When I open archive in 7zip (and another archiver) I see folders without Created, Modified dates. I think user should see the same in Walk(). When I extract files from archive I see folders too.

**Comment by nicola-spb** [comment]
@mholt Yes, you are fixed it. Good job!

**Comment by mholt** [comment]
@nicola-spb Great, good to hear. Note that using `fs.WalkDir()` is inefficient for archives, because of the Go APIs defined by the `fs` package. Using `Extract()` provided directly by this package is more efficient. This archive is probably fine, but you'll notice when the archive has lots of files. (`O(n)` vs. `O(n^2)`)

**Comment by nicola-spb** [comment]
@mholt ok. I'll keep it on mind. 
archiver.WalkDir() is reading better for myself (less code).

P.S. just rewrote the code to using WalkDir() before reading your comment :))))))))))))))))  my archive contains about ~2000 files. Hmmm... I will return Extract :)
