### ISSUE TITLE
Recursive decompression 7z does not work

### ISSUE THREAD

**Issue by drwpeng** [mholt/archiver#362]
7z compressed files nested inside 7z files, recursive decompression will fail.
Err is: `input type must be an io.ReaderAt and io.Seeker because of zip format constraints`

Emm...How about using go-unarr for 7z?

**Comment by drwpeng** [comment]
Same thing with zip

**Comment by mholt** [comment]
Hmm, any ideas how we can make it work? I'm not sure how to get a ReaderAt when we're inside an archive.

**Comment by drwpeng** [comment]
bytes.Reader implements io.Reader, io.ReaderAt, etc.
```
func (z SevenZip) Extract(ctx context.Context, sourceArchive io.Reader, pathsInArchive []string, handleFile FileHandler) error {
	sra, ok := sourceArchive.(seekReaderAt)
	if !ok {
		b, err := io.ReadAll(sourceArchive)
		if err != nil {
			return fmt.Errorf("input type must be an io.ReaderAt and io.Seeker because of zip format constraints")
		}
		sra = bytes.NewReader(b)
	}
	size, err := streamSizeBySeeking(sra)
        ......
}
```

**Comment by mholt** [comment]
But that involves reading all the bytes into memory... 😬 that's not something we can accept, I don't think...

**Comment by drwpeng** [comment]
Isn't the reader always in memory?

**Comment by mholt** [comment]
@drwpeng I think in the majority of use cases, the file is coming from disk or a network stream; not memory. That's just me guessing, but is based on all of my own uses of this lib.

**Comment by bodgit** [comment]
(Maintainer of the sevenzip package here)

You would have to extract the child archive out to a temporary file and then operate on that temporary file.

All of the metadata for the 7z archive is, (and I assume zip is much the same), at the end of the file so you need to jump to the end to get the archive contents and then seek backwards in order to read and extract any files.

The problem is any file extracted from an archive isn't fully seekable because it's more often than not coming from a decompression routine. You can make it seekable-ish; you can seek to the exact same position, or seek forwards by literally reading and discarding bytes, you just can't seek backwards because the decompression routines don't support un-reading bytes. I do exactly this internally in the package; there's an `io.ReadSeeker` implementation that seeks forward by reading and errors if you try and seek backwards.

You would need some sort of buffer to store potentially all of the file data you've extracted so far so when you seek backwards you rely on the buffer to satisfy any reads rather than the archive. The size of that buffer would then be entirely dependent on the size of the extracted file. No problem if it's maybe a few MiB, a problem if it's a few GiB. Alternatively you could internally close and re-extract the file again and seek forwards to the new position, but the performance would potentially be horrendous.

The glib answer is don't put archives in archives 😜 

HTH

**Comment by mholt** [comment]
@bodgit Hey, thanks for chiming in! That is congruent with my own experiences with archive files. I think that is sufficient confirmation that this will be very tricky to implement and, IMO, the use case is very niche.

> The glib answer is don't put archives in archives 😜

Sounds good to me. Thanks!
