### ISSUE TITLE
`sorairolake/lzip-go` repo no longer exists

### ISSUE THREAD

**Issue by rgmz** [mholt/archiver#421]
This is more of an FYI than a bug, as I see this repo is used for the lzip implementation.

It appears that https://github.com/sorairolake/lzip-go no longer exists. Apparently, it's preventing people who don't have a cached version of the code from building projects.

Cross-posted from https://github.com/trufflesecurity/trufflehog/issues/3227

**Comment by mholt** [comment]
Weird.

The Go module proxy still has it cached. I have a copy of the latest on my machine as well.

Is there another lzma lib that works? I tried github.com/ulikunitz/xz/lzma real quick but the tests fail because there isn't a prefix starting with "LZMA" which the spec requires. So I dunno if it's something else, or :shrug:

**Comment by mholt** [comment]
I went ahead and published my copy of it and this project now refers to it.

(I do not intend to maintain it though.)

**Comment by polarathene** [comment]
FWIW that repo is restored. So you can probably switch back to it.
