### ISSUE TITLE
4.0.0-alpha.9 not compatible with https://github.com/STARRY-S/zip/tags  0.2.1

### ISSUE THREAD

**Issue by Slach** [mholt/archiver#428]
## What version of the package or command are you using?

my go.mod 

```
        github.com/mholt/archiver/v4 v4.0.0-alpha.9
	github.com/STARRY-S/zip v0.2.1 // indirect
```

## What are you trying to do?
`go build ./cmd/ -o test`

## What steps did you take?
main.go
```go
import (
	"os"
  	"github.com/mholt/archiver/v4"
)

func main() {
  a := &archiver.CompressedArchive{Archival: archiver.Tar{}}
  reader := os.Open("file.tar")
  if err := z.Extract(ctx, reader, nil, func(ctx context.Context, file archiver.File) error {
     return nil
  })
}
```

## What did you expect to happen, and what actually happened instead?

Successful compilation

## What actually happens

```
1.156 /root/go/pkg/mod/github.com/mholt/archiver/v4@v4.0.0-alpha.9/zip.go:311:16: zu.AppendHeaderAt undefined (type *"github.com/STARRY-S/zip".Updater has no field or method AppendHeaderAt)
```

## How do you think this should be fixed?
I pope it could be easy to fix.

**Comment by mholt** [comment]
I'm not sure I follow. Our `go.mod` uses v0.1.0 of STARRY-S/zip:

https://github.com/mholt/archiver/blob/08f240f2d5a7db209cf5f1066eb60fa7eaafb065/go.mod#L18

So I do not see why v0.2.1 is expected to succeed. :thinking:

**Comment by mholt** [comment]
Looking at this again, I first read it as a bug report (because it uses the bug report template), but I wonder if you're actually asking for a feature request (support a new version of a dependency).

There is no bug here, but there is a request for something new.

Do you want to try https://github.com/mholt/archiver/commit/c932b5626be192c13e6bd822cfffa548cc3bfef5 (or latest on master) to see if that fixes it for you?

**Comment by Slach** [comment]
thanks you, will wait next release

**Comment by mholt** [comment]
Probably will be archiving this (heh) so as not to break existing users.
