### ISSUE TITLE
Is it possible to support 7z archive?

### ISSUE THREAD

**Issue by XiaoMouR** [mholt/archiver#53]
I find that this package has a reference to [lzma](https://github.com/ulikunitz/xz/tree/master/lzma).

**Comment by mholt** [comment]
If there's a pure-Go way to do it, sure thing -- contributions welcome!

**Comment by 89z** [comment]
@mholt this seems to do it:

~~~go
package main

import (
   "fmt"
   "github.com/bodgit/sevenzip"
)

func main() {
   r, err := sevenzip.OpenReader("pe.7z")
   if err != nil {
      panic(err)
   }
   defer r.Close()
   for _, file := range r.File {
      fmt.Println(file.Name)
   }
}
~~~

https://github.com/bodgit/sevenzip

**Comment by mholt** [comment]
Cool; looks like read-only currently, though.

**Comment by 89z** [comment]
Looks like `bodgit/sevenzip` has an issue with some files, I havent had any problems with `saracen/go7z` though.

**Comment by 89z** [comment]
If anyone interested, I made my own package for extracting:

https://pkg.go.dev/github.com/89z/x/extract

It supports `7z`, even `7z` embedded in `exe`. Also supports `zip`, `tar.bz2`,
`tar.gz`, `tar.xz` and `tar.zst`.

**Comment by sergeevabc** [comment]
Well, 7-zip has become [available][1] from Linux since March 2021, let’s not fall behind.

[1] https://www.7-zip.org/download.html

**Comment by coolaj86** [comment]
7z is supported natively by the MacOS Finder as of Catalina... but not the CLI. However, you can get unxz via brew.

7z is worse than USB 3 - too many variations that aren't well standardized or supported.

It's also architecture dependent (meaning endianness sometimes matters). I investigated this heavily and was not able to find any reasonable cross-platform solution in Go, or otherwise.

I did manage to "fix" a bug in one of the popular-ish Go xz libraries, but the funny thing is that it actually still returns success sometimes when it fails due to improper error handling in the C code.

I would love for someone to come up with a solution for this, but for those that are frustrated just know that it is no where near as easy as it would seem. 7z is "open source" in name, but for whatever reason, very few seem to know how to implement it.

**Comment by mholt** [comment]
Thanks AJ. Closing this issue for now, as it seems there aren't great pure-Go solutions for 7z. Feel free to continue discussion and we can reopen when/if this becomes feasible.

**Comment by mholt** [comment]
Huh, nice! Will look more when I'm not mobile.

**Comment by mholt** [comment]
I pushed a very simple, only-lightly-tested commit that implements support for reading 7z files. I only tested it with a simple sample file I found online, but it worked for me.

Not really loving how much the dependency puked all over go.sum and go.mod, but I guess that's what we get for a pure-Go implementation, which I do appreciate.

I'm not a 7z user myself, so any patches or enhancements on this feature should be contributed by others I think.

Thanks for the link, @jmigual !

**Comment by jmigual** [comment]
Wow that was fast! You are welcome 😊

**Comment by sergeevabc** [comment]
Dear @mholt, is there a Windows binary of Archiver with 7z support?
Or any estimate when it will be available to the public?

**Comment by mholt** [comment]
@sergeevabc Archiver v4 does not have any command yet, for any OS; it's just a library for now.
